<?php

namespace Database\Seeders;

use App\Models\Atributo;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/**
 * Class AtributosSeeder
 * @package Database\Seeders
 * @version 2
 */
class AtributosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('atributos')->insert($this->atributos1);
        DB::table('atributos')->insert($this->atributos2);
        Atributo::destroy(72);  /* Evita problemas con IDs en versiones iniciales */
        Atributo::destroy(96);  /* Evita problemas con IDs en versiones iniciales */
        Atributo::destroy(167);  /* Evita problemas con IDs en versiones iniciales */
        Atributo::destroy(170);  /* Evita problemas con IDs en versiones iniciales */
        Atributo::destroy(175);  /* Evita problemas con IDs en versiones iniciales */
        Atributo::destroy(243);  /* Evita problemas con IDs en versiones iniciales */
        Atributo::destroy(311);  /* Evita problemas con IDs en versiones iniciales */
        Atributo::destroy(312);  /* Evita problemas con IDs en versiones iniciales */
    }

    /*
     * TODO: Utilizar factory
     */
    private $atributos1 = [
        // Atributos Pauta Digital, parte 1 (1 > 71)
        ['name' => 'No saluda o indica nombre al iniciar la conversación', 'name_interno' => 'saludo1', 'pauta_id' => 1, 'check_primario' => 0, 'check_ec' => 0, 'id_primario' => 6, 'name_categoria' => 'PENC'],
        ['name' => 'No usa preguntas o frases de conexión inicial', 'name_interno' => 'saludo2', 'pauta_id' => 1, 'check_primario' => 0, 'check_ec' => 0, 'id_primario' => 6, 'name_categoria' => 'PENC'],
        ['name' => 'No Valida contexto indicado previamente', 'name_interno' => 'saludo3', 'pauta_id' => 1, 'check_primario' => 0, 'check_ec' => 0, 'id_primario' => 6, 'name_categoria' => 'PENC'],
        ['name' => 'No se despide y/o realiza de forma poco cordial', 'name_interno' => 'saludo4', 'pauta_id' => 1, 'check_primario' => 0, 'check_ec' => 0, 'id_primario' => 6, 'name_categoria' => 'PENC'],
        ['name' => 'No agradece contacto al despedirse', 'name_interno' => 'saludo5', 'pauta_id' => 1, 'check_primario' => 0, 'check_ec' => 0, 'id_primario' => 6, 'name_categoria' => 'PENC'],
        ['name' => 'Protocolo de saludo y despedida', 'name_interno' => 'saludo6', 'pauta_id' => 1, 'check_primario' => 1, 'check_ec' => 0, 'id_primario' => NULL, 'name_categoria' => 'PENC'],
        ['name' => 'Utiliza frases formales y/o poco cercanas', 'name_interno' => 'frases1', 'pauta_id' => 1, 'check_primario' => 0, 'check_ec' => 0, 'id_primario' => 11, 'name_categoria' => 'PENC'],
        ['name' => 'Utiliza conceptos técnicos', 'name_interno' => 'frases2', 'pauta_id' => 1, 'check_primario' => 0, 'check_ec' => 0, 'id_primario' => 11, 'name_categoria' => 'PENC'],
        ['name' => 'Utiliza frases coloquiales y/o abreviaturas', 'name_interno' => 'frases3', 'pauta_id' => 1, 'check_primario' => 0, 'check_ec' => 0, 'id_primario' => 11, 'name_categoria' => 'PENC'],
        ['name' => 'Utiliza más de un emoticón por comentario', 'name_interno' => 'frases4', 'pauta_id' => 1, 'check_primario' => 0, 'check_ec' => 0, 'id_primario' => 11, 'name_categoria' => 'PENC'],
        ['name' => 'Se comunica de forma simple y cercana', 'name_interno' => 'frases5', 'pauta_id' => 1, 'check_primario' => 1, 'check_ec' => 0, 'id_primario' => NULL, 'name_categoria' => 'PENC'],
        ['name' => 'No manifesta dispoción para atender', 'name_interno' => 'cordialidad1', 'pauta_id' => 1, 'check_primario' => 0, 'check_ec' => 0, 'id_primario' => 16, 'name_categoria' => 'PENC'],
        ['name' => 'No demuestra interes frente a dificultades', 'name_interno' => 'cordialidad2', 'pauta_id' => 1, 'check_primario' => 0, 'check_ec' => 0, 'id_primario' => 16, 'name_categoria' => 'PENC'],
        ['name' => 'No pide disculpas en caso de reclamos', 'name_interno' => 'cordialidad3', 'pauta_id' => 1, 'check_primario' => 0, 'check_ec' => 0, 'id_primario' => 16, 'name_categoria' => 'PENC'],
        ['name' => 'No reduce el conflicto frente a cliente alterados', 'name_interno' => 'cordialidad4', 'pauta_id' => 1, 'check_primario' => 0, 'check_ec' => 0, 'id_primario' => 16, 'name_categoria' => 'PENC'],
        ['name' => 'Demuestra cordialidad y/o reduce conflictos', 'name_interno' => 'cordialidad5', 'pauta_id' => 1, 'check_primario' => 1, 'check_ec' => 0, 'id_primario' => NULL, 'name_categoria' => 'PENC'],
        ['name' => 'No Entrega la información de manera ordenada', 'name_interno' => 'gestionplantillas1', 'pauta_id' => 1, 'check_primario' => 0, 'check_ec' => 0, 'id_primario' => 21, 'name_categoria' => 'PENC'],
        ['name' => 'Usa plantillas o imágenes en exceso', 'name_interno' => 'gestionplantillas2', 'pauta_id' => 1, 'check_primario' => 0, 'check_ec' => 0, 'id_primario' => 21, 'name_categoria' => 'PENC'],
        ['name' => 'Usa plantillas o información irrelevantes para la gestión', 'name_interno' => 'gestionplantillas3', 'pauta_id' => 1, 'check_primario' => 0, 'check_ec' => 0, 'id_primario' => 21, 'name_categoria' => 'PENC'],
        ['name' => 'Vuelve a solicitar la misma información mas de una vez', 'name_interno' => 'gestionplantillas4', 'pauta_id' => 1, 'check_primario' => 0, 'check_ec' => 0, 'id_primario' => 21, 'name_categoria' => 'PENC'],
        ['name' => 'Gestión de plantillas e información', 'name_interno' => 'gestionplantillas5', 'pauta_id' => 1, 'check_primario' => 1, 'check_ec' => 0, 'id_primario' => NULL, 'name_categoria' => 'PENC'],
        ['name' => 'Errores semánticos y/o sintácticos', 'name_interno' => 'ortografia1', 'pauta_id' => 1, 'check_primario' => 0, 'check_ec' => 0, 'id_primario' => 28, 'name_categoria' => 'PENC'],
        ['name' => 'Mal uso de reglas de puntuación (puntos y coma)', 'name_interno' => 'ortografia2', 'pauta_id' => 1, 'check_primario' => 0, 'check_ec' => 0, 'id_primario' => 28, 'name_categoria' => 'PENC'],
        ['name' => 'Errores de escrituras y aplicación de reglas ortográficas (español)', 'name_interno' => 'ortografia3', 'pauta_id' => 1, 'check_primario' => 0, 'check_ec' => 0, 'id_primario' => 28, 'name_categoria' => 'PENC'],
        ['name' => 'Escritura incorrecta de palabras técnicas o de origen extranjero', 'name_interno' => 'ortografia4', 'pauta_id' => 1, 'check_primario' => 0, 'check_ec' => 0, 'id_primario' => 28, 'name_categoria' => 'PENC'],
        ['name' => 'Mal uso del acento diacrítico', 'name_interno' => 'ortografia5', 'pauta_id' => 1, 'check_primario' => 0, 'check_ec' => 0, 'id_primario' => 28, 'name_categoria' => 'PENC'],
        ['name' => 'Uso incorrecto de Mayúsculas/Minúsculas', 'name_interno' => 'ortografia6', 'pauta_id' => 1, 'check_primario' => 0, 'check_ec' => 0, 'id_primario' => 28, 'name_categoria' => 'PENC'],
        ['name' => 'Ortografía y redacción', 'name_interno' => 'ortografia7', 'pauta_id' => 1, 'check_primario' => 1, 'check_ec' => 0, 'id_primario' => NULL, 'name_categoria' => 'PENC'],
        ['name' => 'No personaliza durante la conversación', 'name_interno' => 'personalizacion1', 'pauta_id' => 1, 'check_primario' => 0, 'check_ec' => 0, 'id_primario' => 32, 'name_categoria' => 'PENC'],
        ['name' => 'Trata al cliente por un nombre/usuario erróneo', 'name_interno' => 'personalizacion2', 'pauta_id' => 1, 'check_primario' => 0, 'check_ec' => 0, 'id_primario' => 32, 'name_categoria' => 'PENC'],
        ['name' => 'No Aplica Personalización', 'name_interno' => 'personalizacion3', 'pauta_id' => 1, 'check_primario' => 0, 'check_ec' => 0, 'id_primario' => 32, 'name_categoria' => 'PENC'],
        ['name' => 'Se refiere al Cliente por su nombre', 'name_interno' => 'personalizacion4', 'pauta_id' => 1, 'check_primario' => 1, 'check_ec' => 0, 'id_primario' => NULL, 'name_categoria' => 'PENC'],
        ['name' => 'Proyecta inseguridad o falta de conocimientos', 'name_interno' => 'seguridad1', 'pauta_id' => 1, 'check_primario' => 0, 'check_ec' => 0, 'id_primario' => 35, 'name_categoria' => 'PENC'],
        ['name' => 'Se autocorrige o se contradice en la conversación', 'name_interno' => 'seguridad2', 'pauta_id' => 1, 'check_primario' => 0, 'check_ec' => 0, 'id_primario' => 35, 'name_categoria' => 'PENC'],
        ['name' => 'Proyecta seguridad y dominio de la información', 'name_interno' => 'seguridad3', 'pauta_id' => 1, 'check_primario' => 1, 'check_ec' => 0, 'id_primario' => NULL, 'name_categoria' => 'PENC'],
        ['name' => 'No menciona la necesidad de dejar en espera', 'name_interno' => 'manejosilencios1', 'pauta_id' => 1, 'check_primario' => 0, 'check_ec' => 0, 'id_primario' => 39, 'name_categoria' => 'PENC'],
        ['name' => 'No retoma la conversación en los tiempos definidos', 'name_interno' => 'manejosilencios2', 'pauta_id' => 1, 'check_primario' => 0, 'check_ec' => 0, 'id_primario' => 39, 'name_categoria' => 'PENC'],
        ['name' => 'No agradece el tiempo de espera', 'name_interno' => 'manejosilencios3', 'pauta_id' => 1, 'check_primario' => 0, 'check_ec' => 0, 'id_primario' => 39, 'name_categoria' => 'PENC'],
        ['name' => 'Maneja correctamente los tiempos de espera', 'name_interno' => 'manejosilencios4', 'pauta_id' => 1, 'check_primario' => 1, 'check_ec' => 0, 'id_primario' => NULL, 'name_categoria' => 'PENC'],
        ['name' => 'No realiza aseguramiento de lo informado', 'name_interno' => 'aseguramiento1', 'pauta_id' => 1, 'check_primario' => 0, 'check_ec' => 0, 'id_primario' => 42, 'name_categoria' => 'PENC'],
        ['name' => 'No Aplica Aseguramiento', 'name_interno' => 'aseguramiento2', 'pauta_id' => 1, 'check_primario' => 0, 'check_ec' => 0, 'id_primario' => 42, 'name_categoria' => 'PENC'],
        ['name' => 'Asegura la comprensión de información entregada', 'name_interno' => 'aseguramiento3', 'pauta_id' => 1, 'check_primario' => 1, 'check_ec' => 0, 'id_primario' => NULL, 'name_categoria' => 'PENC'],
        ['name' => 'No realiza ofrecimiento comercial a titular', 'name_interno' => 'ofrecimiento1', 'pauta_id' => 1, 'check_primario' => 0, 'check_ec' => 0, 'id_primario' => 45, 'name_categoria' => 'PENC'],
        ['name' => 'No argumenta o intenta revertir objeciones', 'name_interno' => 'ofrecimiento2', 'pauta_id' => 1, 'check_primario' => 0, 'check_ec' => 0, 'id_primario' => 45, 'name_categoria' => 'PENC'],
        ['name' => 'Realiza ofrecimiento comercial a usuario no autorizado', 'name_interno' => 'ofrecimiento3', 'pauta_id' => 1, 'check_primario' => 0, 'check_ec' => 0, 'id_primario' => 45, 'name_categoria' => 'PENC'],
        ['name' => 'No Aplica Ofrecimiento Comercial', 'name_interno' => 'ofrecimiento4', 'pauta_id' => 1, 'check_primario' => 0, 'check_ec' => 0, 'id_primario' => 45, 'name_categoria' => 'PENC'],
        ['name' => 'Ofrece nuevos productos/servicios', 'name_interno' => 'ofrecimiento5', 'pauta_id' => 1, 'check_primario' => 1, 'check_ec' => 0, 'id_primario' => NULL, 'name_categoria' => 'PENC'],
        ['name' => 'Motivo del llamado', 'name_interno' => 'motivo', 'pauta_id' => 1, 'check_primario' => 0, 'check_ec' => 0, 'id_primario' => NULL, 'name_categoria' => 'Caracterizacion'],
        ['name' => 'Tipo de Gestión 1', 'name_interno' => 'gestion1', 'pauta_id' => 1, 'check_primario' => 0, 'check_ec' => 0, 'id_primario' => NULL, 'name_categoria' => 'Gestion'],
        ['name' => 'Tipo de Gestión 2', 'name_interno' => 'gestion2', 'pauta_id' => 1, 'check_primario' => 0, 'check_ec' => 0, 'id_primario' => NULL, 'name_categoria' => 'Gestion'],
        ['name' => 'Tipo de Gestión 3', 'name_interno' => 'gestion3', 'pauta_id' => 1, 'check_primario' => 0, 'check_ec' => 0, 'id_primario' => NULL, 'name_categoria' => 'Gestion'],
        ['name' => 'Detección de necesidades 1', 'name_interno' => 'deteccion1', 'pauta_id' => 1, 'check_primario' => 0, 'check_ec' => 0, 'id_primario' => NULL, 'name_categoria' => 'Gestion'],
        ['name' => 'Detección de necesidades 2', 'name_interno' => 'deteccion2', 'pauta_id' => 1, 'check_primario' => 0, 'check_ec' => 0, 'id_primario' => NULL, 'name_categoria' => 'Gestion'],
        ['name' => 'Detección de necesidades 3', 'name_interno' => 'deteccion3', 'pauta_id' => 1, 'check_primario' => 0, 'check_ec' => 0, 'id_primario' => NULL, 'name_categoria' => 'Gestion'],
        ['name' => 'Detección de necesidades Full', 'name_interno' => 'deteccion4', 'pauta_id' => 1, 'check_primario' => 0, 'check_ec' => 0, 'id_primario' => NULL, 'name_categoria' => 'Gestion'],
        ['name' => 'Entrega de información correcta y completa 1', 'name_interno' => 'infocorrecta1', 'pauta_id' => 1, 'check_primario' => 0, 'check_ec' => 0, 'id_primario' => NULL, 'name_categoria' => 'Gestion'],
        ['name' => 'Entrega de información correcta y completa 2', 'name_interno' => 'infocorrecta2', 'pauta_id' => 1, 'check_primario' => 0, 'check_ec' => 0, 'id_primario' => NULL, 'name_categoria' => 'Gestion'],
        ['name' => 'Entrega de información correcta y completa 3', 'name_interno' => 'infocorrecta3', 'pauta_id' => 1, 'check_primario' => 0, 'check_ec' => 0, 'id_primario' => NULL, 'name_categoria' => 'Gestion'],
        ['name' => 'Entrega de información correcta y completa Full', 'name_interno' => 'infocorrecta4', 'pauta_id' => 1, 'check_primario' => 0, 'check_ec' => 0, 'id_primario' => NULL, 'name_categoria' => 'Gestion'],
        ['name' => 'Gestiona según proced. en sistema 1', 'name_interno' => 'procedimiento1', 'pauta_id' => 1, 'check_primario' => 0, 'check_ec' => 0, 'id_primario' => NULL, 'name_categoria' => 'Gestion'],
        ['name' => 'Gestiona según proced. en sistema 2', 'name_interno' => 'procedimiento2', 'pauta_id' => 1, 'check_primario' => 0, 'check_ec' => 0, 'id_primario' => NULL, 'name_categoria' => 'Gestion'],
        ['name' => 'Gestiona según proced. en sistema 3', 'name_interno' => 'procedimiento3', 'pauta_id' => 1, 'check_primario' => 0, 'check_ec' => 0, 'id_primario' => NULL, 'name_categoria' => 'Gestion'],
        ['name' => 'Gestiona según proced. en sistema Full', 'name_interno' => 'procedimiento4', 'pauta_id' => 1, 'check_primario' => 0, 'check_ec' => 0, 'id_primario' => NULL, 'name_categoria' => 'Gestion'],
        ['name' => 'Ejecutivo Resuelve el problema de origen en línea 1 ', 'name_interno' => 'resolucion1', 'pauta_id' => 1, 'check_primario' => 0, 'check_ec' => 0, 'id_primario' => NULL, 'name_categoria' => 'Gestion'],
        ['name' => 'Ejecutivo Resuelve el problema de origen en línea 2', 'name_interno' => 'resolucion2', 'pauta_id' => 1, 'check_primario' => 0, 'check_ec' => 0, 'id_primario' => NULL, 'name_categoria' => 'Gestion'],
        ['name' => 'Ejecutivo Resuelve el problema de origen en línea 3', 'name_interno' => 'resolucion3', 'pauta_id' => 1, 'check_primario' => 0, 'check_ec' => 0, 'id_primario' => NULL, 'name_categoria' => 'Gestion'],
        ['name' => 'Error grave en la detección de necesidades y en el analisis de la información', 'name_interno' => 'pecu_deteccion', 'pauta_id' => 1, 'check_primario' => 1, 'check_ec' => 1, 'id_primario' => NULL, 'name_categoria' => 'PEC UF'],
        ['name' => 'Error grave en la gestión por Info incorrecta o incompleta', 'name_interno' => 'pecu_infocorrecta', 'pauta_id' => 1, 'check_primario' => 1, 'check_ec' => 1, 'id_primario' => NULL, 'name_categoria' => 'PEC UF'],
        ['name' => 'Error grave en la gestión por no resolver o resolver de forma errónea', 'name_interno' => 'pecu_procedimiento', 'pauta_id' => 1, 'check_primario' => 1, 'check_ec' => 1, 'id_primario' => NULL, 'name_categoria' => 'PEC UF'],
        ['name' => 'Atención Irrespetuosa y Gestión poco Profesional', 'name_interno' => 'pecu_pocoprofesional', 'pauta_id' => 1, 'check_primario' => 1, 'check_ec' => 1, 'id_primario' => NULL, 'name_categoria' => 'PEC UF'],
        ['name' => 'Manipula al Cliente para concretar venta', 'name_interno' => 'pecu_manipulacliente', 'pauta_id' => 1, 'check_primario' => 1, 'check_ec' => 1, 'id_primario' => NULL, 'name_categoria' => 'PEC UF'],

        // Atributo 72 (no existe)
        ['name' => 'NO EXISTE', 'name_interno' => 'noexiste', 'pauta_id' => 1, 'check_primario' => 1, 'check_ec' => 1, 'id_primario' => NULL, 'name_categoria' => 'NO'],

        // Atributos Pauta Digital, parte 2 (73 > 95)
        ['name' => 'Cierre anticipado de la Interacción ', 'name_interno' => 'pecu_cierreinteraccion', 'pauta_id' => 1, 'check_primario' => 1, 'check_ec' => 1, 'id_primario' => NULL, 'name_categoria' => 'PEC UF'],
        ['name' => 'Provoca o incita el cierre por inactividad', 'name_interno' => 'pecu_provocacierre', 'pauta_id' => 1, 'check_primario' => 1, 'check_ec' => 1, 'id_primario' => NULL, 'name_categoria' => 'PEC UF'],
        ['name' => 'Entrega Beneficio o Excepción comercial fuera de Procedimiento', 'name_interno' => 'pecn_beneficio', 'pauta_id' => 1, 'check_primario' => 1, 'check_ec' => 1, 'id_primario' => NULL, 'name_categoria' => 'PEC NEG'],
        ['name' => 'Fraude', 'name_interno' => 'pecn_fraude', 'pauta_id' => 1, 'check_primario' => 1, 'check_ec' => 1, 'id_primario' => NULL, 'name_categoria' => 'PEC NEG'],
        ['name' => 'No Sondea motivo de renuncia o no Retiene', 'name_interno' => 'pecn_nosondea', 'pauta_id' => 1, 'check_primario' => 1, 'check_ec' => 1, 'id_primario' => NULL, 'name_categoria' => 'PEC NEG'],
        ['name' => 'No Tipifica en sistema o lo realiza de manera incorrecta.', 'name_interno' => 'pecn_tipificacion', 'pauta_id' => 1, 'check_primario' => 1, 'check_ec' => 1, 'id_primario' => NULL, 'name_categoria' => 'PEC NEG'],
        ['name' => 'Validación de Factibilidad Técnica y Comercial', 'name_interno' => 'pecn_factibilidad', 'pauta_id' => 1, 'check_primario' => 1, 'check_ec' => 1, 'id_primario' => NULL, 'name_categoria' => 'PEC NEG'],
        ['name' => 'Otra Gestión Indebida', 'name_interno' => 'pecn_otragestion', 'pauta_id' => 1, 'check_primario' => 1, 'check_ec' => 1, 'id_primario' => NULL, 'name_categoria' => 'PEC NEG'],
        ['name' => 'Entrega información confidencial', 'name_interno' => 'pecc_infoconfidencial', 'pauta_id' => 1, 'check_primario' => 1, 'check_ec' => 1, 'id_primario' => NULL, 'name_categoria' => 'PEC CUMP'],
        ['name' => 'No valida correctamente los datos personales del Cliente', 'name_interno' => 'pecc_novalidadatos', 'pauta_id' => 1, 'check_primario' => 1, 'check_ec' => 1, 'id_primario' => NULL, 'name_categoria' => 'PEC CUMP'],
        ['name' => 'No realiza cierre de negocio según procedimiento', 'name_interno' => 'pecc_cierre', 'pauta_id' => 1, 'check_primario' => 1, 'check_ec' => 1, 'id_primario' => NULL, 'name_categoria' => 'PEC CUMP'],
        ['name' => 'Omite o Indica erróneamente información que es regulada legalmente', 'name_interno' => 'pecc_infoerronea', 'pauta_id' => 1, 'check_primario' => 1, 'check_ec' => 1, 'id_primario' => NULL, 'name_categoria' => 'PEC CUMP'],
        ['name' => 'No comprende el motivo del Cliente', 'name_interno' => 'asistentevirtual1', 'pauta_id' => 1, 'check_primario' => 0, 'check_ec' => 0, 'id_primario' => NULL, 'name_categoria' => 'Caracterizacion'],
        ['name' => 'Cliente insiste mas de una vez en contacto con ejecutivo', 'name_interno' => 'asistentevirtual2', 'pauta_id' => 1, 'check_primario' => 0, 'check_ec' => 0, 'id_primario' => NULL, 'name_categoria' => 'Caracterizacion'],
        ['name' => 'Deriva de forma incorrecta al ejecutivo', 'name_interno' => 'asistentevirtual3', 'pauta_id' => 1, 'check_primario' => 0, 'check_ec' => 0, 'id_primario' => NULL, 'name_categoria' => 'Caracterizacion'],
        ['name' => 'Abandonos previos por parte de otros ejecutivos', 'name_interno' => 'gestionesanteriores1', 'pauta_id' => 1, 'check_primario' => 0, 'check_ec' => 0, 'id_primario' => NULL, 'name_categoria' => 'Caracterizacion'],
        ['name' => 'Abandonos previos por parte del Cliente', 'name_interno' => 'gestionesanteriores2', 'pauta_id' => 1, 'check_primario' => 0, 'check_ec' => 0, 'id_primario' => NULL, 'name_categoria' => 'Caracterizacion'],
        ['name' => 'Más de una conversación reciente por el mismo motivo (NO FCR)', 'name_interno' => 'gestionesanteriores3', 'pauta_id' => 1, 'check_primario' => 0, 'check_ec' => 0, 'id_primario' => NULL, 'name_categoria' => 'Caracterizacion'],
        ['name' => 'Cliente molesto por la atención de la asistente virtual', 'name_interno' => 'usuarios1', 'pauta_id' => 1, 'check_primario' => 0, 'check_ec' => 0, 'id_primario' => NULL, 'name_categoria' => 'Caracterizacion'],
        ['name' => 'Cliente molesto por la atención de los ejecutivos del canal', 'name_interno' => 'usuarios2', 'pauta_id' => 1, 'check_primario' => 0, 'check_ec' => 0, 'id_primario' => NULL, 'name_categoria' => 'Caracterizacion'],
        ['name' => 'Cliente solicita ser contactado telefónicamente', 'name_interno' => 'usuarios3', 'pauta_id' => 1, 'check_primario' => 0, 'check_ec' => 0, 'id_primario' => NULL, 'name_categoria' => 'Caracterizacion'],
        ['name' => 'Retroalimentacion', 'name_interno' => 'retroalimentacion', 'pauta_id' => 1, 'check_primario' => 0, 'check_ec' => 0, 'id_primario' => NULL, 'name_categoria' => 'Memo'],
        ['name' => 'Comentario Interno', 'name_interno' => 'comentario_interno', 'pauta_id' => 1, 'check_primario' => 0, 'check_ec' => 0, 'id_primario' => NULL, 'name_categoria' => 'Memo'],

        // Atributo 96 (no existe)
        ['name' => 'NO EXISTE', 'name_interno' => 'noexiste', 'pauta_id' => 1, 'check_primario' => 1, 'check_ec' => 1, 'id_primario' => NULL, 'name_categoria' => 'NO'],

        // Atributos Pauta Call Voz, parte 1 (97 > 166)
        ['name' => 'Protocolo de Saludo y Despedida', 'name_interno' => 'saludo1', 'pauta_id' => 2, 'check_primario' => 1, 'check_ec' => NULL, 'id_primario' => NULL, 'name_categoria' => 'PENC'],
        ['name' => 'No hace Bienvenida', 'name_interno' => 'saludo2', 'pauta_id' => 2, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 97, 'name_categoria' => 'PENC'],
        ['name' => 'No se despide', 'name_interno' => 'saludo3', 'pauta_id' => 2, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 97, 'name_categoria' => 'PENC'],
        ['name' => 'No utiliza contexto', 'name_interno' => 'saludo4', 'pauta_id' => 2, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 97, 'name_categoria' => 'PENC'],
        ['name' => 'Disposición para la atención', 'name_interno' => 'disposicion1', 'pauta_id' => 2, 'check_primario' => 1, 'check_ec' => NULL, 'id_primario' => NULL, 'name_categoria' => 'PENC'],
        ['name' => 'Interrumpe', 'name_interno' => 'disposicion2', 'pauta_id' => 2, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 101, 'name_categoria' => 'PENC'],
        ['name' => 'No retiene información', 'name_interno' => 'disposicion3', 'pauta_id' => 2, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 101, 'name_categoria' => 'PENC'],
        ['name' => 'Cordialidad y reducción de conflicto', 'name_interno' => 'cordialidad1', 'pauta_id' => 2, 'check_primario' => 1, 'check_ec' => NULL, 'id_primario' => NULL, 'name_categoria' => 'PENC'],
        ['name' => 'No muestra interés', 'name_interno' => 'cordialidad2', 'pauta_id' => 2, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 104, 'name_categoria' => 'PENC'],
        ['name' => 'No reduce conflicto', 'name_interno' => 'cordialidad3', 'pauta_id' => 2, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 104, 'name_categoria' => 'PENC'],
        ['name' => 'No manifiesta disposición', 'name_interno' => 'cordialidad4', 'pauta_id' => 2, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 104, 'name_categoria' => 'PENC'],
        ['name' => 'No pide disculpas', 'name_interno' => 'cordialidad5', 'pauta_id' => 2, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 104, 'name_categoria' => 'PENC'],
        ['name' => 'Manejo de Silencios', 'name_interno' => 'manejosilencios1', 'pauta_id' => 2, 'check_primario' => 1, 'check_ec' => NULL, 'id_primario' => NULL, 'name_categoria' => 'PENC'],
        ['name' => 'No informa Pausa/Hold', 'name_interno' => 'manejosilencios2', 'pauta_id' => 2, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 109, 'name_categoria' => 'PENC'],
        ['name' => 'No interactua', 'name_interno' => 'manejosilencios3', 'pauta_id' => 2, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 109, 'name_categoria' => 'PENC'],
        ['name' => 'No agradece espera', 'name_interno' => 'manejosilencios4', 'pauta_id' => 2, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 109, 'name_categoria' => 'PENC'],
        ['name' => 'Seguridad y Dominio en la conversación con el Cliente', 'name_interno' => 'seguridad1', 'pauta_id' => 2, 'check_primario' => 1, 'check_ec' => NULL, 'id_primario' => NULL, 'name_categoria' => 'PENC'],
        ['name' => 'Inseguridad en conocimientos', 'name_interno' => 'seguridad2', 'pauta_id' => 2, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 113, 'name_categoria' => 'PENC'],
        ['name' => 'Mal manejo de la información', 'name_interno' => 'seguridad3', 'pauta_id' => 2, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 113, 'name_categoria' => 'PENC'],
        ['name' => 'Se contradice y autocorrige', 'name_interno' => 'seguridad4', 'pauta_id' => 2, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 113, 'name_categoria' => 'PENC'],
        ['name' => 'No informa el motivo de uso de datos personales', 'name_interno' => 'seguridad5', 'pauta_id' => 2, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 113, 'name_categoria' => 'PENC'],
        ['name' => 'Comunicación simple y empática', 'name_interno' => 'comunicacion1', 'pauta_id' => 2, 'check_primario' => 1, 'check_ec' => NULL, 'id_primario' => NULL, 'name_categoria' => 'PENC'],
        ['name' => 'Trato cercano y cordial', 'name_interno' => 'comunicacion2', 'pauta_id' => 2, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 118, 'name_categoria' => 'PENC'],
        ['name' => 'Palabras coloquiales', 'name_interno' => 'comunicacion3', 'pauta_id' => 2, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 118, 'name_categoria' => 'PENC'],
        ['name' => 'Usa tecnicismos', 'name_interno' => 'comunicacion4', 'pauta_id' => 2, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 118, 'name_categoria' => 'PENC'],
        ['name' => 'Educar al Cliente en Canales de Autotención', 'name_interno' => 'educacliente1', 'pauta_id' => 2, 'check_primario' => 1, 'check_ec' => NULL, 'id_primario' => NULL, 'name_categoria' => 'PENC'],
        ['name' => 'No menciona otros canales', 'name_interno' => 'educacliente2', 'pauta_id' => 2, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 122, 'name_categoria' => 'PENC'],
        ['name' => 'N/A Por posible molestia', 'name_interno' => 'educacliente3', 'pauta_id' => 2, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 122, 'name_categoria' => 'PENC'],
        ['name' => 'N/A Sin opciones', 'name_interno' => 'educacliente4', 'pauta_id' => 2, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 122, 'name_categoria' => 'PENC'],
        ['name' => 'Aseguramiento', 'name_interno' => 'aseguramiento1', 'pauta_id' => 2, 'check_primario' => 1, 'check_ec' => NULL, 'id_primario' => NULL, 'name_categoria' => 'PENC'],
        ['name' => 'No valida información entregada', 'name_interno' => 'aseguramiento2', 'pauta_id' => 2, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 126, 'name_categoria' => 'PENC'],
        ['name' => 'N/A por transfer/Callback', 'name_interno' => 'aseguramiento3', 'pauta_id' => 2, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 126, 'name_categoria' => 'PENC'],
        ['name' => 'N/A canal incorrecto', 'name_interno' => 'aseguramiento4', 'pauta_id' => 2, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 126, 'name_categoria' => 'PENC'],
        ['name' => 'N/A por posible molestia', 'name_interno' => 'aseguramiento5', 'pauta_id' => 2, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 126, 'name_categoria' => 'PENC'],
        ['name' => 'N/A cliente asegura info', 'name_interno' => 'aseguramiento6', 'pauta_id' => 2, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 126, 'name_categoria' => 'PENC'],
        ['name' => 'Ofrecimiento Comercial', 'name_interno' => 'ofrecimientocomercial1', 'pauta_id' => 2, 'check_primario' => 1, 'check_ec' => NULL, 'id_primario' => NULL, 'name_categoria' => 'PENC'],
        ['name' => 'No Asesora', 'name_interno' => 'ofrecimientocomercial2', 'pauta_id' => 2, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 132, 'name_categoria' => 'PENC'],
        ['name' => 'No Ofrece Acorde', 'name_interno' => 'ofrecimientocomercial3', 'pauta_id' => 2, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 132, 'name_categoria' => 'PENC'],
        ['name' => 'N/A Plataforma Especialista', 'name_interno' => 'ofrecimientocomercial4', 'pauta_id' => 2, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 132, 'name_categoria' => 'PENC'],
        ['name' => 'N/A Cliente Indispuesto', 'name_interno' => 'ofrecimientocomercial5', 'pauta_id' => 2, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 132, 'name_categoria' => 'PENC'],
        ['name' => 'N/A No es titular o usuario registrado', 'name_interno' => 'ofrecimientocomercial6', 'pauta_id' => 2, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 132, 'name_categoria' => 'PENC'],
        ['name' => 'N/A Sin Factibilidad Comercial', 'name_interno' => 'ofrecimientocomercial7', 'pauta_id' => 2, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 132, 'name_categoria' => 'PENC'],
        ['name' => 'N/A Sin Factibilidad Técnica', 'name_interno' => 'ofrecimientocomercial8', 'pauta_id' => 2, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 132, 'name_categoria' => 'PENC'],
        ['name' => 'N/A Problemas Técnicos', 'name_interno' => 'ofrecimientocomercial9', 'pauta_id' => 2, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 132, 'name_categoria' => 'PENC'],
        ['name' => 'N/A Otros', 'name_interno' => 'ofrecimientocomercial10', 'pauta_id' => 2, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 132, 'name_categoria' => 'PENC'],
        ['name' => 'Frases de Enganche y Argumentación ', 'name_interno' => 'frasesenganche1', 'pauta_id' => 2, 'check_primario' => 1, 'check_ec' => NULL, 'id_primario' => NULL, 'name_categoria' => 'PENC'],
        ['name' => 'No argumenta', 'name_interno' => 'frasesenganche2', 'pauta_id' => 2, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 142, 'name_categoria' => 'PENC'],
        ['name' => 'Usa argumentos erroneos', 'name_interno' => 'frasesenganche3', 'pauta_id' => 2, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 142, 'name_categoria' => 'PENC'],
        ['name' => 'N/A Sin ofrecimiento comercial', 'name_interno' => 'frasesenganche4', 'pauta_id' => 2, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 142, 'name_categoria' => 'PENC'],
        ['name' => 'Error grave en la detección de necesidades y en el analisis de la información', 'name_interno' => 'pecu_deteccion', 'pauta_id' => 2, 'check_primario' => 1, 'check_ec' => 1, 'id_primario' => NULL, 'name_categoria' => 'PEC UF'],
        ['name' => 'Error grave en la gestión por Info incorrecta o incompleta', 'name_interno' => 'pecu_gestionincorrecta', 'pauta_id' => 2, 'check_primario' => 1, 'check_ec' => 1, 'id_primario' => NULL, 'name_categoria' => 'PEC UF'],
        ['name' => 'Error grave en la gestión por no resolver o resolver de forma errónea', 'name_interno' => 'pecu_noresuelve', 'pauta_id' => 2, 'check_primario' => 1, 'check_ec' => 1, 'id_primario' => NULL, 'name_categoria' => 'PEC UF'],
        ['name' => 'Atendió de forma grosera', 'name_interno' => 'pecu_atenciongrosera', 'pauta_id' => 2, 'check_primario' => 1, 'check_ec' => 1, 'id_primario' => NULL, 'name_categoria' => 'PEC UF'],
        ['name' => 'Se desentiende o es poco profesional', 'name_interno' => 'pecu_pocoprofesional', 'pauta_id' => 2, 'check_primario' => 1, 'check_ec' => 1, 'id_primario' => NULL, 'name_categoria' => 'PEC UF'],
        ['name' => 'Manipula al Cliente para concretar venta', 'name_interno' => 'pecu_manipulacliente', 'pauta_id' => 2, 'check_primario' => 1, 'check_ec' => 1, 'id_primario' => NULL, 'name_categoria' => 'PEC UF'],
        ['name' => 'No sondea motivo de renuncia o no Retiene', 'name_interno' => 'pecn_nosondea', 'pauta_id' => 2, 'check_primario' => 1, 'check_ec' => 1, 'id_primario' => NULL, 'name_categoria' => 'PEC NEG'],
        ['name' => 'Descalificó a ENTEL', 'name_interno' => 'pecn_descalificaentel', 'pauta_id' => 2, 'check_primario' => 1, 'check_ec' => 1, 'id_primario' => NULL, 'name_categoria' => 'PEC NEG'],
        ['name' => 'Entrega Beneficio o Excepción comercial fuera de Procedimiento', 'name_interno' => 'pecn_beneficiofueraproc', 'pauta_id' => 2, 'check_primario' => 1, 'check_ec' => 1, 'id_primario' => NULL, 'name_categoria' => 'PEC NEG'],
        ['name' => 'Fraude', 'name_interno' => 'pecn_fraude', 'pauta_id' => 2, 'check_primario' => 1, 'check_ec' => 1, 'id_primario' => NULL, 'name_categoria' => 'PEC NEG'],
        ['name' => 'No libera la línea una vez finalizada la llamada', 'name_interno' => 'pecn_noliberalinea', 'pauta_id' => 2, 'check_primario' => 1, 'check_ec' => 1, 'id_primario' => NULL, 'name_categoria' => 'PEC NEG'],
        ['name' => 'Validación de Factibilidad Técnica y Comercial', 'name_interno' => 'pecn_factibilidad', 'pauta_id' => 2, 'check_primario' => 1, 'check_ec' => 1, 'id_primario' => NULL, 'name_categoria' => 'PEC NEG'],
        ['name' => 'Ingreso a Sistema', 'name_interno' => 'pecn_notipificasistema', 'pauta_id' => 2, 'check_primario' => 1, 'check_ec' => 1, 'id_primario' => NULL, 'name_categoria' => 'PEC NEG'],
        ['name' => 'Otra Gestión Indebida', 'name_interno' => 'pecn_otragestion', 'pauta_id' => 2, 'check_primario' => 1, 'check_ec' => 1, 'id_primario' => NULL, 'name_categoria' => 'PEC NEG'],
        ['name' => 'Niega Escalamiento o Ingreso de Reclamo', 'name_interno' => 'pecc_niegaescalamiento', 'pauta_id' => 2, 'check_primario' => 1, 'check_ec' => 1, 'id_primario' => NULL, 'name_categoria' => 'PEC CUMP'],
        ['name' => 'Omite o Indica erróneamente información que es regulada legalmente', 'name_interno' => 'pecc_omiteinformacion', 'pauta_id' => 2, 'check_primario' => 1, 'check_ec' => 1, 'id_primario' => NULL, 'name_categoria' => 'PEC CUMP'],
        ['name' => 'Entregó información confidencial', 'name_interno' => 'pecc_infoconfidencial', 'pauta_id' => 2, 'check_primario' => 1, 'check_ec' => 1, 'id_primario' => NULL, 'name_categoria' => 'PEC CUMP'],
        ['name' => 'Cierre de negocios', 'name_interno' => 'pecc_cierrenegocios', 'pauta_id' => 2, 'check_primario' => 1, 'check_ec' => 1, 'id_primario' => NULL, 'name_categoria' => 'PEC CUMP'],
        ['name' => 'No Valida correctamente los datos personales del cliente', 'name_interno' => 'pecc_novalidadatos', 'pauta_id' => 2, 'check_primario' => 1, 'check_ec' => 1, 'id_primario' => NULL, 'name_categoria' => 'PEC CUMP'],
        ['name' => 'No coordina correctamente Despacho/Entrega/Instalación', 'name_interno' => 'pecc_despacho', 'pauta_id' => 2, 'check_primario' => 1, 'check_ec' => 1, 'id_primario' => NULL, 'name_categoria' => 'PEC CUMP'],
        ['name' => 'Responsable PEC', 'name_interno' => 'pec_responsable', 'pauta_id' => 2, 'check_primario' => 1, 'check_ec' => 1, 'id_primario' => NULL, 'name_categoria' => 'PEC'],

        // Atributo 167 (no existe)
        ['name' => 'NO EXISTE', 'name_interno' => 'noexiste', 'pauta_id' => 1, 'check_primario' => 1, 'check_ec' => 1, 'id_primario' => NULL, 'name_categoria' => 'NO'],

        // Atributos Pauta Call Voz, parte 2 (168 > 169)
        ['name' => 'Ruidos o problemas de calidad en el audio', 'name_interno' => 'otro_ruidoenllamada', 'pauta_id' => 2, 'check_primario' => 0, 'check_ec' => NULL, 'id_primario' => NULL, 'name_categoria' => 'Caracterizacion'],
        ['name' => 'Uso de frases tipo o scripts para la comunicación', 'name_interno' => 'otro_frasesyscripts', 'pauta_id' => 2, 'check_primario' => 0, 'check_ec' => NULL, 'id_primario' => NULL, 'name_categoria' => 'Caracterizacion'],

        // Atributo 170 (no existe)
        ['name' => 'NO EXISTE', 'name_interno' => 'noexiste', 'pauta_id' => 1, 'check_primario' => 1, 'check_ec' => 1, 'id_primario' => NULL, 'name_categoria' => 'NO'],

        // Atributos Pauta Call Voz, parte 3 (171 > 174)
        ['name' => 'Tipo de Negocio', 'name_interno' => 'otro_tiponegocio', 'pauta_id' => 2, 'check_primario' => 0, 'check_ec' => NULL, 'id_primario' => NULL, 'name_categoria' => 'Caracterizacion'],
        ['name' => 'Ofrecimiento de más de una Línea', 'name_interno' => 'otro_ofrecimientomultilinea', 'pauta_id' => 2, 'check_primario' => 0, 'check_ec' => NULL, 'id_primario' => NULL, 'name_categoria' => 'Caracterizacion'],
        ['name' => 'Ofrecimiento de equipo', 'name_interno' => 'otro_ofrecimientoequipo', 'pauta_id' => 2, 'check_primario' => 0, 'check_ec' => NULL, 'id_primario' => NULL, 'name_categoria' => 'Caracterizacion'],
        ['name' => 'Ofrecimiento de accesorios', 'name_interno' => 'otro_ofrecimientoaccesorio', 'pauta_id' => 2, 'check_primario' => 0, 'check_ec' => NULL, 'id_primario' => NULL, 'name_categoria' => 'Caracterizacion'],

        // Atributo 175 (no existe)
        ['name' => 'NO EXISTE', 'name_interno' => 'noexiste', 'pauta_id' => 1, 'check_primario' => 1, 'check_ec' => 1, 'id_primario' => NULL, 'name_categoria' => 'NO'],

        // Atributos Pauta Call Voz, parte 4 (176 > 177)
        ['name' => 'Retroalimentacion', 'name_interno' => 'retroalimentacion', 'pauta_id' => 2, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => NULL, 'name_categoria' => 'Memo'],
        ['name' => 'Comentario Interno', 'name_interno' => 'comentario_interno', 'pauta_id' => 2, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => NULL, 'name_categoria' => 'Memo'],

        // Atributo Pauta Digital, resagado (178)
        ['name' => 'No informa el motivo de uso de datos personales', 'name_interno' => 'seguridad4', 'pauta_id' => 1, 'check_primario' => 0, 'check_ec' => 0, 'id_primario' => 35, 'name_categoria' => 'PENC'],

        // Atributos Pauta Call Voz, parte 4 (179 > 199)
        ['name' => 'Motivo del llamado', 'name_interno' => 'motivo', 'pauta_id' => 2, 'check_primario' => 0, 'check_ec' => 0, 'id_primario' => NULL, 'name_categoria' => 'Caracterizacion'],
        ['name' => 'Tipo de Gestión', 'name_interno' => 'tipogestion1', 'pauta_id' => 2, 'check_primario' => 0, 'check_ec' => 0, 'id_primario' => NULL, 'name_categoria' => 'Gestión'],
        ['name' => 'Tipo de Gestión', 'name_interno' => 'tipogestion2', 'pauta_id' => 2, 'check_primario' => 0, 'check_ec' => 0, 'id_primario' => NULL, 'name_categoria' => 'Gestión'],
        ['name' => 'Tipo de Gestión', 'name_interno' => 'tipogestion3', 'pauta_id' => 2, 'check_primario' => 0, 'check_ec' => 0, 'id_primario' => NULL, 'name_categoria' => 'Gestión'],
        ['name' => 'Detección de necesidades/sondeo/analisis/revisión', 'name_interno' => 'deteccion1', 'pauta_id' => 2, 'check_primario' => 0, 'check_ec' => 0, 'id_primario' => NULL, 'name_categoria' => 'Gestión'],
        ['name' => 'Detección de necesidades/sondeo/analisis/revisión', 'name_interno' => 'deteccion2', 'pauta_id' => 2, 'check_primario' => 0, 'check_ec' => 0, 'id_primario' => NULL, 'name_categoria' => 'Gestión'],
        ['name' => 'Detección de necesidades/sondeo/analisis/revisión', 'name_interno' => 'deteccion3', 'pauta_id' => 2, 'check_primario' => 0, 'check_ec' => 0, 'id_primario' => NULL, 'name_categoria' => 'Gestión'],
        ['name' => 'Detección de necesidades/sondeo/analisis/revisión FULL', 'name_interno' => 'deteccion4', 'pauta_id' => 2, 'check_primario' => 0, 'check_ec' => 0, 'id_primario' => NULL, 'name_categoria' => 'Gestión'],
        ['name' => 'Entrega de información correcta y completa', 'name_interno' => 'infocorrecta1', 'pauta_id' => 2, 'check_primario' => 0, 'check_ec' => 0, 'id_primario' => NULL, 'name_categoria' => 'Gestión'],
        ['name' => 'Entrega de información correcta y completa', 'name_interno' => 'infocorrecta2', 'pauta_id' => 2, 'check_primario' => 0, 'check_ec' => 0, 'id_primario' => NULL, 'name_categoria' => 'Gestión'],
        ['name' => 'Entrega de información correcta y completa', 'name_interno' => 'infocorrecta3', 'pauta_id' => 2, 'check_primario' => 0, 'check_ec' => 0, 'id_primario' => NULL, 'name_categoria' => 'Gestión'],
        ['name' => 'Entrega de información correcta y completa FULL', 'name_interno' => 'infocorrecta4', 'pauta_id' => 2, 'check_primario' => 0, 'check_ec' => 0, 'id_primario' => NULL, 'name_categoria' => 'Gestión'],
        ['name' => 'Gestiona según proced. en sistema', 'name_interno' => 'gestiona1', 'pauta_id' => 2, 'check_primario' => 0, 'check_ec' => 0, 'id_primario' => NULL, 'name_categoria' => 'Gestión'],
        ['name' => 'Gestiona según proced. en sistema', 'name_interno' => 'gestiona2', 'pauta_id' => 2, 'check_primario' => 0, 'check_ec' => 0, 'id_primario' => NULL, 'name_categoria' => 'Gestión'],
        ['name' => 'Gestiona según proced. en sistema', 'name_interno' => 'gestiona3', 'pauta_id' => 2, 'check_primario' => 0, 'check_ec' => 0, 'id_primario' => NULL, 'name_categoria' => 'Gestión'],
        ['name' => 'Gestiona según proced. en sistema FULL', 'name_interno' => 'gestiona4', 'pauta_id' => 2, 'check_primario' => 0, 'check_ec' => 0, 'id_primario' => NULL, 'name_categoria' => 'Gestión'],
        ['name' => 'Ejecutivo Resuelve el problema de origen en línea', 'name_interno' => 'resolucion1', 'pauta_id' => 2, 'check_primario' => 0, 'check_ec' => 0, 'id_primario' => NULL, 'name_categoria' => 'Gestión'],
        ['name' => 'Ejecutivo Resuelve el problema de origen en línea', 'name_interno' => 'resolucion2', 'pauta_id' => 2, 'check_primario' => 0, 'check_ec' => 0, 'id_primario' => NULL, 'name_categoria' => 'Gestión'],
        ['name' => 'Ejecutivo Resuelve el problema de origen en línea', 'name_interno' => 'resolucion3', 'pauta_id' => 2, 'check_primario' => 0, 'check_ec' => 0, 'id_primario' => NULL, 'name_categoria' => 'Gestión'],
        ['name' => 'Ejecutivo Resuelve el problema de origen en línea FULL', 'name_interno' => 'resolucion4', 'pauta_id' => 2, 'check_primario' => 0, 'check_ec' => 0, 'id_primario' => NULL, 'name_categoria' => 'Gestión'],
        ['name' => 'Descripción del Caso', 'name_interno' => 'descripcion_caso', 'pauta_id' => 2, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => NULL, 'name_categoria' => 'Memo'],
        ['name' => 'Respuesta del Ejecutivo', 'name_interno' => 'respuesta_ejecutivo', 'pauta_id' => 2, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => NULL, 'name_categoria' => 'Memo'],
    ];
    public $atributos2 = [
        // Atributos Pauta Ventas Remotas (201 > 312)
        ['name' => 'Presentación del Ejecutivo', 'name_interno' => 'presentacion1', 'pauta_id' => 3, 'check_primario' => 1, 'check_ec' => NULL, 'id_primario' => NULL, 'name_categoria' => 'PENC'],
        ['name' => 'No Saluda cordialmente', 'name_interno' => 'presentacion2', 'pauta_id' => 3, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 201, 'name_categoria' => 'PENC'],
        ['name' => 'No se identifica frente al Cliente', 'name_interno' => 'presentacion3', 'pauta_id' => 3, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 201, 'name_categoria' => 'PENC'],
        ['name' => 'Frases de Enganche y Conexión', 'name_interno' => 'frasesenganche1', 'pauta_id' => 3, 'check_primario' => 1, 'check_ec' => NULL, 'id_primario' => NULL, 'name_categoria' => 'PENC'],
        ['name' => 'No realiza frase de conexión', 'name_interno' => 'frasesenganche2', 'pauta_id' => 3, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 204, 'name_categoria' => 'PENC'],
        ['name' => 'No realiza frase de enganche', 'name_interno' => 'frasesenganche3', 'pauta_id' => 3, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 204, 'name_categoria' => 'PENC'],
        ['name' => 'Personalización', 'name_interno' => 'personalizacion1', 'pauta_id' => 3, 'check_primario' => 1, 'check_ec' => NULL, 'id_primario' => NULL, 'name_categoria' => 'PENC'],
        ['name' => 'No Personaliza', 'name_interno' => 'personalizacion2', 'pauta_id' => 3, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 207, 'name_categoria' => 'PENC'],
        ['name' => 'Personaliza incorrectamente', 'name_interno' => 'personalizacion3', 'pauta_id' => 3, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 207, 'name_categoria' => 'PENC'],
        ['name' => 'Detección de Necesidades', 'name_interno' => 'deteccion1', 'pauta_id' => 3, 'check_primario' => 1, 'check_ec' => NULL, 'id_primario' => NULL, 'name_categoria' => 'PENC'],
        ['name' => 'No Aplica', 'name_interno' => 'deteccion2', 'pauta_id' => 3, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 210, 'name_categoria' => 'PENC'],
        ['name' => 'No Valida las necesidades del Cliente', 'name_interno' => 'deteccion3', 'pauta_id' => 3, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 210, 'name_categoria' => 'PENC'],
        ['name' => 'No sondea posibilidad de hacer negocio con multilínea', 'name_interno' => 'deteccion4', 'pauta_id' => 3, 'check_primario' => NULL, 'check_ec' => 1, 'id_primario' => 210, 'name_categoria' => 'PEC'],
        ['name' => 'Evaluación Comercial / Técnica', 'name_interno' => 'evaluacion1', 'pauta_id' => 3, 'check_primario' => 1, 'check_ec' => NULL, 'id_primario' => NULL, 'name_categoria' => 'PENC'],
        ['name' => 'No Comprueba Restricciones Comerciales', 'name_interno' => 'evaluacion2', 'pauta_id' => 3, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 214, 'name_categoria' => 'PENC'],
        ['name' => 'No Comprueba Factibilidad Técnica', 'name_interno' => 'evaluacion3', 'pauta_id' => 3, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 214, 'name_categoria' => 'PENC'],
        ['name' => 'Continua con negocio a pesar que el Cliente no califica', 'name_interno' => 'evaluacion4', 'pauta_id' => 3, 'check_primario' => NULL, 'check_ec' => 1, 'id_primario' => 214, 'name_categoria' => 'PEC'],
        ['name' => 'Entrega Información confidencial de los sistema de evaluación comercial', 'name_interno' => 'evaluacion5', 'pauta_id' => 3, 'check_primario' => NULL, 'check_ec' => 1, 'id_primario' => 214, 'name_categoria' => 'PEC'],
        ['name' => 'Manipula la información para lograr una evaluación positiva en NEC', 'name_interno' => 'evaluacion6', 'pauta_id' => 3, 'check_primario' => NULL, 'check_ec' => 1, 'id_primario' => 214, 'name_categoria' => 'PEC'],
        ['name' => 'Ofrece la mejor alternativa', 'name_interno' => 'mejoralternativa1', 'pauta_id' => 3, 'check_primario' => 1, 'check_ec' => NULL, 'id_primario' => NULL, 'name_categoria' => 'PENC'],
        ['name' => 'No Aplica', 'name_interno' => 'mejoralternativa2', 'pauta_id' => 3, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 220, 'name_categoria' => 'PENC'],
        ['name' => 'No asesorar en la mejor alternativa', 'name_interno' => 'mejoralternativa3', 'pauta_id' => 3, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 220, 'name_categoria' => 'PENC'],
        ['name' => 'Argumentación', 'name_interno' => 'argumentacion1', 'pauta_id' => 3, 'check_primario' => 1, 'check_ec' => NULL, 'id_primario' => NULL, 'name_categoria' => 'PENC'],
        ['name' => 'Ejecutivo usa argumentos no comprobados', 'name_interno' => 'argumentacion2', 'pauta_id' => 3, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 223, 'name_categoria' => 'PENC'],
        ['name' => 'Usa argumentos que van en contra de la permanencia', 'name_interno' => 'argumentacion3', 'pauta_id' => 3, 'check_primario' => NULL, 'check_ec' => 1, 'id_primario' => 223, 'name_categoria' => 'PEC'],
        ['name' => 'Manipula información o procedimiento para concretar venta', 'name_interno' => 'argumentacion4', 'pauta_id' => 3, 'check_primario' => NULL, 'check_ec' => 1, 'id_primario' => 223, 'name_categoria' => 'PEC'],
        ['name' => 'Condiciones Especificas del Plan Contratado', 'name_interno' => 'condiciones1', 'pauta_id' => 3, 'check_primario' => 1, 'check_ec' => NULL, 'id_primario' => NULL, 'name_categoria' => 'PENC'],
        ['name' => 'No indica correctamente el cargo fijo', 'name_interno' => 'condiciones2', 'pauta_id' => 3, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 227, 'name_categoria' => 'PENC'],
        ['name' => 'No indica correctamente los minutos incluidos/saldo', 'name_interno' => 'condiciones3', 'pauta_id' => 3, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 227, 'name_categoria' => 'PENC'],
        ['name' => 'No indica correctamente la cuota de datos/velocidad', 'name_interno' => 'condiciones4', 'pauta_id' => 3, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 227, 'name_categoria' => 'PENC'],
        ['name' => 'No indica correctamente las apps ilimitadas incluidas', 'name_interno' => 'condiciones5', 'pauta_id' => 3, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 227, 'name_categoria' => 'PENC'],
        ['name' => 'No indica correctamente las restricciones de minutos/mb ilimitados', 'name_interno' => 'condiciones6', 'pauta_id' => 3, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 227, 'name_categoria' => 'PENC'],
        ['name' => 'No indica correctamente el saldo mínimo para bolsas SMS', 'name_interno' => 'condiciones7', 'pauta_id' => 3, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 227, 'name_categoria' => 'PENC'],
        ['name' => 'Omite o Entrega información incorrecta que afectara al cliente', 'name_interno' => 'condiciones8', 'pauta_id' => 3, 'check_primario' => NULL, 'check_ec' => 1, 'id_primario' => 227, 'name_categoria' => 'PEC'],
        ['name' => 'Ingresa erróneamente en sistema plan informado', 'name_interno' => 'condiciones9', 'pauta_id' => 3, 'check_primario' => NULL, 'check_ec' => 1, 'id_primario' => 227, 'name_categoria' => 'PEC'],
        ['name' => 'Promociones asociadas al negocio', 'name_interno' => 'promociones1', 'pauta_id' => 3, 'check_primario' => 1, 'check_ec' => NULL, 'id_primario' => NULL, 'name_categoria' => 'PENC'],
        ['name' => 'No Aplica', 'name_interno' => 'promociones2', 'pauta_id' => 3, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 236, 'name_categoria' => 'PENC'],
        ['name' => 'Indica erróneamente beneficios asociados', 'name_interno' => 'promociones3', 'pauta_id' => 3, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 236, 'name_categoria' => 'PENC'],
        ['name' => 'Indica erróneamente vigencia', 'name_interno' => 'promociones4', 'pauta_id' => 3, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 236, 'name_categoria' => 'PENC'],
        ['name' => 'No realiza ofrecimiento de equipo según campaña', 'name_interno' => 'promociones5', 'pauta_id' => 3, 'check_primario' => NULL, 'check_ec' => 1, 'id_primario' => 236, 'name_categoria' => 'PEC'],
        ['name' => 'Omite o Entrega información incorrecta que afectara al cliente', 'name_interno' => 'promociones6', 'pauta_id' => 3, 'check_primario' => NULL, 'check_ec' => 1, 'id_primario' => 236, 'name_categoria' => 'PEC'],
        ['name' => 'Ingresa erróneamente en sistema oferta entregada', 'name_interno' => 'promociones7', 'pauta_id' => 3, 'check_primario' => NULL, 'check_ec' => 1, 'id_primario' => 236, 'name_categoria' => 'PEC'],
        // Atributo 243 (no existe)
        ['name' => 'Negocio Rechazado posterior al audio', 'name_interno' => 'promociones8', 'pauta_id' => 3, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 236, 'name_categoria' => 'PENC'],
        ['name' => 'Facturación', 'name_interno' => 'facturacion1', 'pauta_id' => 3, 'check_primario' => 1, 'check_ec' => NULL, 'id_primario' => NULL, 'name_categoria' => 'PENC'],
        ['name' => 'No Indica/gestiona medio de notificación', 'name_interno' => 'facturacion2', 'pauta_id' => 3, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 244, 'name_categoria' => 'PENC'],
        ['name' => 'No Informa el cargo proporcional en boleta', 'name_interno' => 'facturacion3', 'pauta_id' => 3, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 244, 'name_categoria' => 'PENC'],
        ['name' => 'No Indica ciclo de facturación y fecha de vencimiento', 'name_interno' => 'facturacion4', 'pauta_id' => 3, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 244, 'name_categoria' => 'PENC'],
        ['name' => 'Omite o Entrega información incorrecta que afectara al cliente', 'name_interno' => 'facturacion5', 'pauta_id' => 3, 'check_primario' => NULL, 'check_ec' => 1, 'id_primario' => 244, 'name_categoria' => 'PEC'],
        ['name' => 'Ingresa erróneamente en sistema datos para la fact.', 'name_interno' => 'facturacion6', 'pauta_id' => 3, 'check_primario' => NULL, 'check_ec' => 1, 'id_primario' => 244, 'name_categoria' => 'PEC'],
        ['name' => 'Cargos de Habilitación', 'name_interno' => 'cargos1', 'pauta_id' => 3, 'check_primario' => 1, 'check_ec' => NULL, 'id_primario' => NULL, 'name_categoria' => 'PENC'],
        ['name' => 'No Aplica', 'name_interno' => 'cargos2', 'pauta_id' => 3, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 250, 'name_categoria' => 'PENC'],
        ['name' => 'Indica erróneamente los cargos de equipo/sim', 'name_interno' => 'cargos3', 'pauta_id' => 3, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 250, 'name_categoria' => 'PENC'],
        ['name' => 'Indica erróneamente los cargos de instalación', 'name_interno' => 'cargos4', 'pauta_id' => 3, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 250, 'name_categoria' => 'PENC'],
        ['name' => 'Indica erróneamente la forma de pago', 'name_interno' => 'cargos5', 'pauta_id' => 3, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 250, 'name_categoria' => 'PENC'],
        ['name' => 'Omite o Entrega información incorrecta que afectara al cliente', 'name_interno' => 'cargos6', 'pauta_id' => 3, 'check_primario' => NULL, 'check_ec' => 1, 'id_primario' => 250, 'name_categoria' => 'PEC'],
        ['name' => 'Ingresa erróneamente en sistema los cargos de habilitación', 'name_interno' => 'cargos7', 'pauta_id' => 3, 'check_primario' => NULL, 'check_ec' => 1, 'id_primario' => 250, 'name_categoria' => 'PEC'],
        ['name' => 'Equipo', 'name_interno' => 'equipos1', 'pauta_id' => 3, 'check_primario' => 1, 'check_ec' => NULL, 'id_primario' => NULL, 'name_categoria' => 'PENC'],
        ['name' => 'No Aplica', 'name_interno' => 'equipos2', 'pauta_id' => 3, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 257, 'name_categoria' => 'PENC'],
        ['name' => 'No informa correctamente el modelo', 'name_interno' => 'equipos3', 'pauta_id' => 3, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 257, 'name_categoria' => 'PENC'],
        ['name' => 'No informa correctamente las características', 'name_interno' => 'equipos4', 'pauta_id' => 3, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 257, 'name_categoria' => 'PENC'],
        ['name' => 'Omite o Entrega información incorrecta que afectara al cliente', 'name_interno' => 'equipos5', 'pauta_id' => 3, 'check_primario' => NULL, 'check_ec' => 1, 'id_primario' => 257, 'name_categoria' => 'PEC'],
        ['name' => 'Validación de Datos del Cliente', 'name_interno' => 'validacion1', 'pauta_id' => 3, 'check_primario' => 1, 'check_ec' => NULL, 'id_primario' => NULL, 'name_categoria' => 'PENC'],
        ['name' => 'Rut', 'name_interno' => 'validacion2', 'pauta_id' => 3, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 262, 'name_categoria' => 'PENC'],
        ['name' => 'Nombre Completo', 'name_interno' => 'validacion3', 'pauta_id' => 3, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 262, 'name_categoria' => 'PENC'],
        ['name' => 'Fecha de Nacimiento', 'name_interno' => 'validacion4', 'pauta_id' => 3, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 262, 'name_categoria' => 'PENC'],
        ['name' => 'Dirección Postal', 'name_interno' => 'validacion5', 'pauta_id' => 3, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 262, 'name_categoria' => 'PENC'],
        ['name' => 'Correo eletrónico', 'name_interno' => 'validacion6', 'pauta_id' => 3, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 262, 'name_categoria' => 'PENC'],
        ['name' => 'Teléfono a portar', 'name_interno' => 'validacion7', 'pauta_id' => 3, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 262, 'name_categoria' => 'PENC'],
        ['name' => 'Serie CI', 'name_interno' => 'validacion8', 'pauta_id' => 3, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 262, 'name_categoria' => 'PENC'],
        ['name' => 'Empresa donadora', 'name_interno' => 'validacion9', 'pauta_id' => 3, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 262, 'name_categoria' => 'PENC'],
        ['name' => 'Imei', 'name_interno' => 'validacion10', 'pauta_id' => 3, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 262, 'name_categoria' => 'PENC'],
        ['name' => 'Dirección despacho', 'name_interno' => 'validacion11', 'pauta_id' => 3, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 262, 'name_categoria' => 'PENC'],
        ['name' => 'Dos Teléfono de contacto', 'name_interno' => 'validacion12', 'pauta_id' => 3, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 262, 'name_categoria' => 'PENC'],
        ['name' => 'No valida datos críticos para el negocio', 'name_interno' => 'validacion13', 'pauta_id' => 3, 'check_primario' => NULL, 'check_ec' => 1, 'id_primario' => 262, 'name_categoria' => 'PEC'],
        ['name' => 'Ingresa erróneamente en sistema datos personales del cliente', 'name_interno' => 'validacion14', 'pauta_id' => 3, 'check_primario' => NULL, 'check_ec' => 1, 'id_primario' => 262, 'name_categoria' => 'PEC'],
        ['name' => 'Coordinación Despacho/Activación/Instalación', 'name_interno' => 'despacho1', 'pauta_id' => 3, 'check_primario' => 1, 'check_ec' => NULL, 'id_primario' => NULL, 'name_categoria' => 'PENC'],
        ['name' => 'Indica erróneamente horario de entrega/instalación', 'name_interno' => 'despacho2', 'pauta_id' => 3, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 276, 'name_categoria' => 'PENC'],
        ['name' => 'Informa plazos y procedimiento de portabilidad', 'name_interno' => 'despacho3', 'pauta_id' => 3, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 276, 'name_categoria' => 'PENC'],
        ['name' => 'No indica documentación necesaria', 'name_interno' => 'despacho4', 'pauta_id' => 3, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 276, 'name_categoria' => 'PENC'],
        ['name' => 'No valida datos críticos para el negocio', 'name_interno' => 'despacho5', 'pauta_id' => 3, 'check_primario' => NULL, 'check_ec' => 1, 'id_primario' => 276, 'name_categoria' => 'PEC'],
        ['name' => 'Ingresa erróneamente en sistema datos personales del cliente', 'name_interno' => 'despacho6', 'pauta_id' => 3, 'check_primario' => NULL, 'check_ec' => 1, 'id_primario' => 276, 'name_categoria' => 'PEC'],
        ['name' => 'No valida información para entrega de terceros', 'name_interno' => 'despacho7', 'pauta_id' => 3, 'check_primario' => NULL, 'check_ec' => 1, 'id_primario' => 276, 'name_categoria' => 'PEC'],
        ['name' => 'Scripts Obligatorios y legales', 'name_interno' => 'scripts1', 'pauta_id' => 3, 'check_primario' => 1, 'check_ec' => NULL, 'id_primario' => NULL, 'name_categoria' => 'PENC'],
        ['name' => 'No lee el extracto u omite algún párrafo', 'name_interno' => 'scripts2', 'pauta_id' => 3, 'check_primario' => NULL, 'check_ec' => 1, 'id_primario' => 283, 'name_categoria' => 'PEC'],
        ['name' => 'Altera de manera importante el contexto y/o el sentido', 'name_interno' => 'scripts3', 'pauta_id' => 3, 'check_primario' => NULL, 'check_ec' => 1, 'id_primario' => 283, 'name_categoria' => 'PEC'],
        ['name' => 'Lo realiza a una persona distinta al titular', 'name_interno' => 'scripts4', 'pauta_id' => 3, 'check_primario' => NULL, 'check_ec' => 1, 'id_primario' => 283, 'name_categoria' => 'PEC'],
        ['name' => 'No realiza pregunta de aceptación explicita del negocio', 'name_interno' => 'scripts5', 'pauta_id' => 3, 'check_primario' => NULL, 'check_ec' => 1, 'id_primario' => 283, 'name_categoria' => 'PEC'],
        ['name' => 'Despedida e información de cierre', 'name_interno' => 'despedida1', 'pauta_id' => 3, 'check_primario' => 1, 'check_ec' => NULL, 'id_primario' => NULL, 'name_categoria' => 'PENC'],
        ['name' => 'Atención Respetuosa', 'name_interno' => 'atencion1', 'pauta_id' => 3, 'check_primario' => 1, 'check_ec' => NULL, 'id_primario' => NULL, 'name_categoria' => 'PENC'],
        ['name' => 'Irónico', 'name_interno' => 'atencion2', 'pauta_id' => 3, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 289, 'name_categoria' => 'PENC'],
        ['name' => 'Prepotente', 'name_interno' => 'atencion3', 'pauta_id' => 3, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 289, 'name_categoria' => 'PENC'],
        ['name' => 'Despectivo - poco profesional', 'name_interno' => 'atencion4', 'pauta_id' => 3, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 289, 'name_categoria' => 'PENC'],
        ['name' => 'Realiza ruidos molestos', 'name_interno' => 'atencion5', 'pauta_id' => 3, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 289, 'name_categoria' => 'PENC'],
        ['name' => 'Interrumpe', 'name_interno' => 'atencion6', 'pauta_id' => 3, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 289, 'name_categoria' => 'PENC'],
        ['name' => 'Actitud desafiante, conflictiva, despectiva, discriminatoria o arrogante al cliente', 'name_interno' => 'atencion7', 'pauta_id' => 3, 'check_primario' => NULL, 'check_ec' => 1, 'id_primario' => 289, 'name_categoria' => 'PEC'],
        ['name' => 'Fluidez y Lenguaje', 'name_interno' => 'lenguaje1', 'pauta_id' => 3, 'check_primario' => 1, 'check_ec' => NULL, 'id_primario' => NULL, 'name_categoria' => 'PENC'],
        ['name' => 'Falta de ritmo', 'name_interno' => 'lenguaje2', 'pauta_id' => 3, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 296, 'name_categoria' => 'PENC'],
        ['name' => 'No ajusta volumen de voz', 'name_interno' => 'lenguaje3', 'pauta_id' => 3, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 296, 'name_categoria' => 'PENC'],
        ['name' => 'No pronuncia correctamente', 'name_interno' => 'lenguaje4', 'pauta_id' => 3, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 296, 'name_categoria' => 'PENC'],
        ['name' => 'No utiliza correctamente el vocabulario/muletillas', 'name_interno' => 'lenguaje5', 'pauta_id' => 3, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 296, 'name_categoria' => 'PENC'],
        ['name' => 'Utiliza tecnicismos', 'name_interno' => 'lenguaje6', 'pauta_id' => 3, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 296, 'name_categoria' => 'PENC'],
        ['name' => 'Claridad y Orden', 'name_interno' => 'claridad1', 'pauta_id' => 3, 'check_primario' => 1, 'check_ec' => NULL, 'id_primario' => NULL, 'name_categoria' => 'PENC'],
        ['name' => 'No Entrega de información de manera ordenada lógicamente de acuerdo a la campaña. ', 'name_interno' => 'claridad2', 'pauta_id' => 3, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 302, 'name_categoria' => 'PENC'],
        ['name' => 'Vuelve a solicitar la misma información', 'name_interno' => 'claridad3', 'pauta_id' => 3, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 302, 'name_categoria' => 'PENC'],
        ['name' => 'Manejo y Dominio en la conversación con el Cliente', 'name_interno' => 'dominio1', 'pauta_id' => 3, 'check_primario' => 1, 'check_ec' => NULL, 'id_primario' => NULL, 'name_categoria' => 'PENC'],
        ['name' => 'Falta seguridad para vender', 'name_interno' => 'dominio2', 'pauta_id' => 3, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 305, 'name_categoria' => 'PENC'],
        ['name' => 'No manifiesta interés ni disposición con el Cliente', 'name_interno' => 'dominio3', 'pauta_id' => 3, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 305, 'name_categoria' => 'PENC'],
        ['name' => 'Falta de seguridad al responder preguntas', 'name_interno' => 'dominio4', 'pauta_id' => 3, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 305, 'name_categoria' => 'PENC'],
        ['name' => 'Retroalimentacion', 'name_interno' => 'retroalimentacion', 'pauta_id' => 3, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => NULL, 'name_categoria' => 'Memo'],
        ['name' => 'Comentario Interno', 'name_interno' => 'comentario_interno', 'pauta_id' => 3, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => NULL, 'name_categoria' => 'Memo'],
        // Atributo 311 y 312 (no existe)
        ['name' => 'Descripción del Caso', 'name_interno' => 'descripcion_caso', 'pauta_id' => 3, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => NULL, 'name_categoria' => 'Memo'],
        ['name' => 'Respuesta del Ejecutivo', 'name_interno' => 'respuesta_ejecutivo', 'pauta_id' => 3, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => NULL, 'name_categoria' => 'Memo'],

        ['name' => 'No informa Canales de postventa consulta/reclamo', 'name_interno' => 'despedida2', 'pauta_id' => 3, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 288, 'name_categoria' => 'PENC'],
        ['name' => 'No informa canales de reagendamiento de visita', 'name_interno' => 'despedida3', 'pauta_id' => 3, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 288, 'name_categoria' => 'PENC'],
        ['name' => 'No indica pasos para ingresar a hbo max', 'name_interno' => 'despedida4', 'pauta_id' => 3, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 288, 'name_categoria' => 'PENC'],
        ['name' => 'No se despide de manera cordial', 'name_interno' => 'despedida5', 'pauta_id' => 3, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 288, 'name_categoria' => 'PENC'],
        ['name' => 'Rebate de Objeciones', 'name_interno' => 'objeciones1', 'pauta_id' => 3, 'check_primario' => 1, 'check_ec' => NULL, 'id_primario' => NULL, 'name_categoria' => 'PENC'],
        ['name' => 'No Aplica', 'name_interno' => 'objeciones2', 'pauta_id' => 3, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 317, 'name_categoria' => 'PENC'],
        ['name' => 'El ejecutivo usa argumento no comprobados', 'name_interno' => 'objeciones3', 'pauta_id' => 3, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 317, 'name_categoria' => 'PENC'],
        ['name' => 'No se despide de manera cordial', 'name_interno' => 'objeciones4', 'pauta_id' => 3, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 317, 'name_categoria' => 'PENC'],
        ['name' => 'Manipula información o procedimiento para concretar venta', 'name_interno' => 'objeciones5', 'pauta_id' => 3, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 317, 'name_categoria' => 'PENC'],
        // Atributos nuevos Pauta Call Voz - 322 a 327 - Ingreso de Reclamos
        ['name' => 'Ingresa reclamos a plataformas Back Office', 'name_interno' => 'reclamos1', 'pauta_id' => 2, 'check_primario' => 1, 'check_ec' => NULL, 'id_primario' => NULL, 'name_categoria' => 'Reclamos'],
        ['name' => 'Valida correctamente los datos para derivar correctamente al back', 'name_interno' => 'reclamos2', 'pauta_id' => 2, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 322, 'name_categoria' => 'Reclamos'],
        ['name' => 'Ingresa ticket y observaciones según procedimiento', 'name_interno' => 'reclamos3', 'pauta_id' => 2, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 322, 'name_categoria' => 'Reclamos'],
        ['name' => 'Informa correctamente plazos de respuesta', 'name_interno' => 'reclamos4', 'pauta_id' => 2, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 322, 'name_categoria' => 'Reclamos'],
        ['name' => 'Indica número de reclamo', 'name_interno' => 'reclamos5', 'pauta_id' => 2, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 322, 'name_categoria' => 'Reclamos'],
        ['name' => 'Menciona canales de consulta para el reclamo', 'name_interno' => 'reclamos6', 'pauta_id' => 2, 'check_primario' => NULL, 'check_ec' => NULL, 'id_primario' => 322, 'name_categoria' => 'Reclamos'],

    ];

}
